spring.profiles.active=dev

springBoot.swagger.show=true

ftp.username=root
ftp.password=yudao2019
ftp.host=192.168.0.200
ftp.port=2341
ftp.workDir=/yudao
ftp.encoding=utf-8
ftp.root=/
ftp.MaxTotal=100
ftp.MinIdel=2
ftp.MaxIdle=5
ftp.MaxWaitMillis=3000
ftp.defaultTimeoutSecond = 60
ftp.dataTimeoutSecond=60

ftp.httpAddress=http://192.168.0.200:8082/
ftp.httpAddress2=http://192.168.0.200:8082/
file.path=/opt/resource/

#\u89E3\u51B3\u52A0\u8F7Dswagger\u62A5\u5F02\u5E38\u95EE\u9898 java.lang.NumberFormatException: For input string: ""
logging.level.io.swagger.models.parameters.AbstractSerializableParameter=error

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=LEGACYHTML5
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.content-type=text/html
spring.thymeleaf.cache=false

web.host=http://rdc.yudaotec.com:8118

memoq.host=https://memoq.datalsp.com:8081/memoqserverhttpapi/v1/
memoq.username=PM-demo
memoq.password=PM@demo12
memoq.tbGuid=699ead2e-35d1-4c5e-b17d-5c1774ce25ba